Agregados generador y clasificador
HernanG234/edp-2023-ci pull request #28
Opened 2023-09-12 02:18 UTC by MatiasSantucho

2023-09-12 02:18 UTC, MatiasSantucho commented
Agregue generador y clasificador

2023-09-13 18:05 UTC, HernanG234 requested changes
Los scripts están bien. En el clasificador quizás tenga más sentido usar un `case` pero lo dejo a tu criterio. Lo único que te voy a pedir es que remuevas la carpeta outputs de git, no nos interesa tener todas esas imágenes en el repo, y si las necesitamos las podemos regenerar con el generador.

2023-09-22 18:28 UTC, HernanG234 requested changes
El código está bien, pero el clasificador no debería saber la extensión de los archivos. La idea era sacar la metadata de los mismos usando `file` como dice el enunciado, ya que el generador los deja sin extensión. No lo consideramos mal si dejás la extensión, siempre y cuando los clasifiques usando `file`. Recordá que las extensiones en linux son simplemente sugerencias pero no nos importan realmente.

2023-09-29 13:11 UTC, HernanG234 approved these changes
LGTM

2023-09-29 13:11 UTC, merged