Prieto tp
HernanG234/edp-2023-ci pull request #32
Opened 2023-09-15 23:21 UTC by TobiasPrieto

Queda hecho todo el primer contenedor

2023-09-22 18:43 UTC, HernanG234 requested changes, later dismissed
Casi que estamo!

2023-09-22 18:43 UTC, HernanG234 commented on estudiantes/prieto-tobias/tp/README.md
> +Pasos a ejecutar:
Vamooo un README, muchas gracias! jaja

2023-09-22 18:43 UTC, HernanG234 commented on estudiantes/prieto-tobias/tp/usuario/Dockerfile
> +
Faltaría el entrypoint pero ya casi!

2023-09-22 18:43 UTC, HernanG234 commented on estudiantes/prieto-tobias/tp/usuario/opt/src/clasificador.sh
> +    else
Enhancement: Si hay algun archivo que no es de ninguno de esos 3 tipos, lo va a considerar imagen. Podrías agregar una regex más y sino descartar el archivo nomá

2023-09-22 18:43 UTC, HernanG234 commented on estudiantes/prieto-tobias/tp/usuario/opt/src/monitor.sh
> +    top -b -n 1 | head -n 10
No estoy muy seguro de esto.

2023-09-22 18:43 UTC, HernanG234 commented on estudiantes/prieto-tobias/tp/usuario/opt/src/monitor.sh
> +    ps aux | wc -l
Hay una linea extra con el nombre de las columnas!

2023-09-22 18:43 UTC, HernanG234 commented on estudiantes/prieto-tobias/tp/usuario/opt/src/monitor.sh
> +    df -h
Está bien peeeeero podríamos filtrar un poquito y solo ver el espacio libre en cada filesystem.

2023-09-25 13:36 UTC, HernanG234 reviewed
El resto pinta bien! Espero el cierre que el último commit dice que falta chequear!

2023-09-25 13:36 UTC, HernanG234 commented on estudiantes/prieto-tobias/tp/usuario/Dockerfile
> +RUN apt-get install -y tree
tree y nano son innecesarias!

2023-09-26 17:13 UTC, adalessandro approved these changes

2023-09-26 17:14 UTC, merged